name: Rebuild Discourse Prod2
concurrency: fixed-prod2
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: run launcher rebuild command via ssh
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DISCOURSE_PROD2_HOST }}
          username: ${{ secrets.DISCOURSE_PROD2_USERNAME }}
          password: ${{ secrets.DISCOURSE_PROD2_PASSWORD }}
          port: 22
          command_timeout: 200m
          script: |
            docker exec -w /var/www/discourse -i app git pull --rebase
            /var/discourse/launcher rebuild app
